name: Trigger First Workflow

on:
  workflow_dispatch: # Manually trigger the first workflow
  schedule:
    - cron: "0 0 * * *" # Schedule (every day at midnight)

jobs:
  update:
    runs-on: ubuntu-latest
    environment: Testing
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Generate unique identifier
        id: generate_id
        run: echo "::set-output name=id::$(uuidgen)"

      - name: Save parameters to environment variables
        run: |
          echo "param1=value1" > parameters.txt
          echo "param2=value2" >> parameters.txt

      - name: Save Unique ID to GitHub Secrets
        run: |
          gh secret set UNIQUE_ID_${{ steps.generate_id.outputs.id }} --body ${{ steps.generate_id.outputs.id }}
          gh secret set PARAMETERS_${{ steps.generate_id.outputs.id }} --body "$(cat parameters.txt)"
