name: Trigger First Workflow

on:
  workflow_dispatch: # Manually trigger the first workflow
  schedule:
    - cron: "0 0 * * *" # Schedule (every day at midnight)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate unique identifier
        id: generate_id
        run: echo "::set-output name=id::$(uuidgen)"

      - name: Save parameters to cache
        run: |
          echo "param1=value1" > parameters_${{ steps.generate_id.outputs.id }}.txt
          echo "param2=value2" >> parameters_${{ steps.generate_id.outputs.id }}.txt

      - name: Cache parameters
        uses: actions/cache@v3
        with:
          path: parameters_${{ steps.generate_id.outputs.id }}.txt
          key: ${{ steps.generate_id.outputs.id }}
