name: Trigger First Workflow

on:
  workflow_dispatch: # Manually trigger the first workflow
  schedule:
    - cron: "0 0 * * *" # Schedule (every day at midnight)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate unique identifier
        id: generate_id
        run: echo "::set-output name=id::$(uuidgen)"

      - name: Set parameters
        run: |
          echo "param1=value1" > parameters_${{ steps.generate_id.outputs.id }}.txt
          echo "param2=value2" >> parameters_${{ steps.generate_id.outputs.id }}.txt

      - name: Upload parameters as artifact
        uses: actions/upload-artifact@v3
        with:
          name: parameters-${{ steps.generate_id.outputs.id }}
          path: parameters_${{ steps.generate_id.outputs.id }}.txt

      - name: Save unique ID for later use
        run: echo "${{ steps.generate_id.outputs.id }}" > unique_id.txt

      - name: Upload unique ID as artifact
        uses: actions/upload-artifact@v3
        with:
          name: unique-id
          path: unique_id.txt
