name: Delayed Second Workflow

on:
  workflow_run:
    workflows: ["Trigger First Workflow"] # Exact name of the first workflow
    types:
      - completed

jobs:
  delayed-start:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 60 seconds
        run: sleep $((60)) # 6 hours in seconds

      - name: Restore parameters from cache
        uses: actions/cache@v3
        with:
          path: parameters_${{ github.run_id }}.txt
          key: ${{ github.run_id }}

      - name: Read parameters from file
        id: read_params
        run: |
          source parameters_${{ github.run_id }}.txt
          echo "::set-output name=param1::$param1"
          echo "::set-output name=param2::$param2"

      - name: Use parameters
        run: |
          echo "Parameter 1: ${{ steps.read_params.outputs.param1 }}"
          echo "Parameter 2: ${{ steps.read_params.outputs.param2 }}"
