name: Delayed Second Workflow

on:
  workflow_run:
    workflows: ["Trigger First Workflow"]
    types:
      - completed

jobs:
  delayed-start:
    runs-on: ubuntu-latest
    steps:
      - name: Get unique identifier from triggering workflow
        run: echo "Unique ID: ${{ github.event.workflow_run.outputs.unique_id }}"

      - name: Wait for 6 hours
        run: sleep $((6 * 3600)) # 6 hours in seconds

      - name: Download corresponding parameters artifact
        uses: actions/download-artifact@v3
        with:
          name: parameters-${{ github.event.workflow_run.outputs.unique_id }}

      - name: Read parameters from file
        id: read_params
        run: |
          source parameters_${{ github.event.workflow_run.outputs.unique_id }}.txt
          echo "::set-output name=param1::$param1"
          echo "::set-output name=param2::$param2"

      - name: Use parameters
        run: |
          echo "Parameter 1: ${{ steps.read_params.outputs.param1 }}"
          echo "Parameter 2: ${{ steps.read_params.outputs.param2 }}"
