name: Delayed Second Workflow

on:
  workflow_run:
    workflows: ["Trigger First Workflow"] # Exact name of the first workflow
    types:
      - completed

jobs:
  delayed-start:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 6 hours
        run: sleep $((6 * 3600)) # 6 hours in seconds

      - name: Download parameters artifact
        uses: actions/download-artifact@v3
        with:
          name: parameters-${{ github.event.workflow_run.outputs.unique_id }}

      - name: Read parameters from file
        id: read_params
        run: |
          if [ -f parameters_${{ github.event.workflow_run.outputs.unique_id }}.txt ]; then
            source parameters_${{ github.event.workflow_run.outputs.unique_id }}.txt
            echo "::set-output name=param1::$param1"
            echo "::set-output name=param2::$param2"
          else
            echo "Parameter file not found!"
            exit 1
          fi

      - name: Use parameters
        run: |
          echo "Parameter 1: ${{ steps.read_params.outputs.param1 }}"
          echo "Parameter 2: ${{ steps.read_params.outputs.param2 }}"
