name: Delayed Second Workflow

on:
  workflow_run:
    workflows: ["Trigger First Workflow"] # Exact name of the first workflow
    types:
      - completed

jobs:
  delayed-start:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 6 hours
        run: sleep $((60)) # 6 hours in seconds

      - name: Download unique ID artifact
        uses: actions/download-artifact@v3
        with:
          name: unique-id

      - name: Read unique ID
        id: read_id
        run: |
          unique_id=$(cat unique_id.txt)
          echo "Unique ID: $unique_id"
          echo "::set-output name=unique_id::$unique_id"

      - name: Download corresponding parameters artifact
        uses: actions/download-artifact@v3
        with:
          name: parameters-${{ steps.read_id.outputs.unique_id }}

      - name: Read parameters from file
        id: read_params
        run: |
          source parameters_${{ steps.read_id.outputs.unique_id }}.txt
          echo "::set-output name=param1::$param1"
          echo "::set-output name=param2::$param2"

      - name: Use parameters
        run: |
          echo "Parameter 1: ${{ steps.read_params.outputs.param1 }}"
          echo "Parameter 2: ${{ steps.read_params.outputs.param2 }}"
