name: Delayed Second Workflow

on:
  workflow_run:
    workflows: ["Trigger First Workflow"] # Exact name of the first workflow
    types:
      - completed

jobs:
  delayed-start:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 6 hours
        run: sleep $((6 * 3600)) # 6 hours in seconds

      - name: Retrieve unique ID from secrets
        id: retrieve_id
        run: |
          UNIQUE_ID=$(gh secret get UNIQUE_ID_${{ github.run_id }})
          echo "Unique ID: $UNIQUE_ID"
          echo "::set-output name=unique_id::$UNIQUE_ID"

      - name: Retrieve parameters from secrets
        id: retrieve_params
        run: |
          PARAMETERS=$(gh secret get PARAMETERS_${{ steps.retrieve_id.outputs.unique_id }})
          echo "$PARAMETERS" > parameters.txt
          source parameters.txt
          echo "::set-output name=param1::$param1"
          echo "::set-output name=param2::$param2"

      - name: Use parameters
        run: |
          echo "Parameter 1: ${{ steps.retrieve_params.outputs.param1 }}"
          echo "Parameter 2: ${{ steps.retrieve_params.outputs.param2 }}"
